### ISSUE TITLE
Applications not being announced

### ISSUE THREAD

**Issue by kylecrouse** [kylecrouse/output-racing#11]
Script execution says it is completing on Google's end and applicant shows in pending list, but no message is sent to Discord.

**Comment by kylecrouse** [comment]
```
Feb 17 19:26:32 ip-172-31-8-151 web: TypeError: Cannot read property 'send' of undefined
Feb 17 19:26:32 ip-172-31-8-151 web: at handleApplication (/var/app/current/bot/lib/applications.js:245:23)
Feb 17 19:26:32 ip-172-31-8-151 web: at runMicrotasks (<anonymous>)
Feb 17 19:26:32 ip-172-31-8-151 web: at processTicksAndRejections (internal/process/task_queues.js:97:5)
Feb 17 19:26:32 ip-172-31-8-151 web: at async /var/app/current/server/index.js:92:7
```
